<h1> Exercise 4</h1>
<p>Onur Bozkurtoğlu</p>
<p>20170808044</p>
<h2>9    Numpy</h2>
<h4> Generate matrices A, with random Gaussian entries, B, a Toeplitz matrix, where A elements of Rn×m and B elements of Rm×m, for n = 200, m = 500. </h4>

In [6]:
import numpy as np
import scipy.linalg as sl
import time

n = 200
m = 500
A = np.random.normal(0, 1, (n,m))
c = np.random.rand(m)
r = np.random.rand(m)
B = sl.toeplitz(c,r)
print("A: ")
print(A)
print("B: ")
print(B)

A: 
[[-0.45269208 -0.21667445 -0.35556721 ... -1.17903524  0.37326562
   0.0149939 ]
 [ 1.14439295 -1.28779368 -0.70927342 ... -0.59086774  0.15554805
   1.80945531]
 [ 0.1839974   0.46023868  0.55223262 ...  0.87167178  1.17628567
   2.11052789]
 ...
 [ 1.13385034 -0.11488453 -2.36529018 ...  0.32187909  0.01066171
   0.55990071]
 [-0.15981965 -0.35992909 -1.41690438 ...  0.19473277 -1.87369412
   0.19461615]
 [-0.40658029  0.67371376  0.03400602 ...  0.51887721  0.21538303
   0.12913357]]
B: 
[[0.34144001 0.93431864 0.53437553 ... 0.9112123  0.0246802  0.78277916]
 [0.83140314 0.34144001 0.93431864 ... 0.06540571 0.9112123  0.0246802 ]
 [0.31171413 0.83140314 0.34144001 ... 0.91797033 0.06540571 0.9112123 ]
 ...
 [0.09781151 0.18820692 0.83093231 ... 0.34144001 0.93431864 0.53437553]
 [0.33394215 0.09781151 0.18820692 ... 0.83140314 0.34144001 0.93431864]
 [0.53461506 0.33394215 0.09781151 ... 0.31171413 0.83140314 0.34144001]]


<h3> Exercise 9.1: Matrix operations </h3>
<h4> Calculate A + A, AA^T, A^TA and AB. Write a function that computes A(B − λI) for any λ. </h4>

In [11]:
print("A + A: ")
print(A + A)

print("AA^T: ")
print(np.dot(A, A.T))

print("A^TA: ")
print(np.dot(A.T, A))

print("AB: ")
print(np.dot(A, B))

def func1(A, B, Lambda):
    C = B - Lambda * (np.eye(m))
    D = np.dot(A, C)
    return D

print("A(B - λI): ")
print(func1(A, B, 3))

A + A: 
[[-0.90538415 -0.43334889 -0.71113442 ... -2.35807048  0.74653124
   0.02998779]
 [ 2.2887859  -2.57558736 -1.41854685 ... -1.18173548  0.3110961
   3.61891063]
 [ 0.36799479  0.92047737  1.10446524 ...  1.74334357  2.35257135
   4.22105578]
 ...
 [ 2.26770069 -0.22976906 -4.73058036 ...  0.64375818  0.02132341
   1.11980142]
 [-0.3196393  -0.71985818 -2.83380875 ...  0.38946554 -3.74738823
   0.38923231]
 [-0.81316057  1.34742751  0.06801204 ...  1.03775442  0.43076605
   0.25826713]]
AA^T: 
[[ 5.47709283e+02  6.82593803e+00  2.58619167e+01 ...  1.58105725e+01
   2.37572257e+01  1.30842241e+01]
 [ 6.82593803e+00  4.48095203e+02  1.24008620e+00 ...  1.57533731e+01
   1.50589225e+01 -2.95674219e-01]
 [ 2.58619167e+01  1.24008620e+00  5.21089031e+02 ... -1.34458066e+01
   1.29312620e+01  1.81593738e+01]
 ...
 [ 1.58105725e+01  1.57533731e+01 -1.34458066e+01 ...  5.36770094e+02
   8.02201244e+00  5.19780981e-02]
 [ 2.37572257e+01  1.50589225e+01  1.29312620e+01 ...  8.02201244e+00

<h3> Exercise 9.2: Solving a linear system </h3>
<h4> Generate a vector b with m entries and solve Bx = b. </h4>

In [12]:
b = np.random.rand(m, 1)
print("x for Bx=b: ")
print(np.linalg.solve(B,b))

x for Bx=b: 
[[ 3.11979906e+01]
 [ 3.17690929e+01]
 [ 3.69007737e+01]
 [-1.04856333e+01]
 [-1.91313925e+01]
 [-3.80188381e+01]
 [-4.36099858e+01]
 [-5.10548301e+01]
 [ 2.67560450e-01]
 [-2.87444301e+01]
 [ 1.43301953e+00]
 [ 5.57610419e+00]
 [ 1.86203373e+01]
 [ 1.39092975e+01]
 [-1.14614901e+00]
 [ 1.79495034e+01]
 [-8.92986296e+00]
 [-2.24761366e+00]
 [-3.09545392e+01]
 [ 8.75849956e+00]
 [ 1.22876085e+01]
 [ 2.13599284e+01]
 [ 2.12341355e+01]
 [ 6.66709130e+01]
 [ 1.11557795e+01]
 [-5.39930647e+00]
 [ 5.74354146e+00]
 [ 1.77514158e+01]
 [-3.61199114e+00]
 [-1.08839691e+01]
 [-8.57109410e+00]
 [-1.42998450e+01]
 [-1.58681880e+01]
 [-1.81271610e+01]
 [-1.71220006e+01]
 [-3.04496201e+01]
 [-8.97295400e+00]
 [ 1.23970709e+00]
 [-1.70590764e+01]
 [-2.51497719e+01]
 [-1.39211371e+01]
 [ 5.64095501e+00]
 [-7.80165285e+00]
 [-4.05035264e+00]
 [-2.00104977e+00]
 [ 3.09094566e+00]
 [-1.95152503e+01]
 [-8.31585178e+00]
 [ 9.23646455e+00]
 [ 1.78958727e+01]
 [ 1.35652043e+01]
 [ 3.61564494e+01]

<h3> Exercise 9.3: Norms </h3>
<h4> Compute the Frobenius norm of A: ||A||F and the infinity norm of B: ||B||inf. Also find the largest and
smallest singular values of B. </h4>

In [16]:
print("||A||F: ")
print(np.linalg.norm(A, "fro"))
print("B||B||inf: ")
print(np.linalg.norm(B, np.inf))
print("Largest singular value of B: ")
print(np.linalg.norm(B, 2))
print("Smallest singular value of B: ")
print(np.linalg.norm(B, -2))

||A||F: 
316.8646329143076
B||B||inf: 
260.7465655978824
Largest singular value of B: 
255.25249080523182
Smallest singular value of B: 
0.0014610783097979759


<h3> Exercise 9.4: Power iteration </h3>
<h4> Generate a matrix Z, n × n, with Gaussian entries, and use the power iteration to find the largest
eigenvalue and corresponding eigenvector of Z. How many iterations are needed till convergence? </h4>

In [19]:
Z = np.random.normal(3,1, (n, n))
a, b = np.linalg.eig(Z)
print("The largest eigenvalue: ")
print(a.max())
print("The eigenvector: ")
print(b)

The largest eigenvalue: 
(598.506863788306+0j)
The eigenvector: 
[[ 0.07078833+0.j         -0.00351375+0.j          0.04605597+0.0174106j
  ... -0.02700003+0.j          0.04986597+0.j
  -0.03303231+0.j        ]
 [ 0.06725607+0.j         -0.01080672+0.j         -0.01504392-0.02047787j
  ... -0.16941399+0.j         -0.06084852+0.j
  -0.00299413+0.j        ]
 [ 0.07272483+0.j          0.0020644 +0.j          0.02330864+0.09371975j
  ...  0.04213048+0.j         -0.01030013+0.j
  -0.03469104+0.j        ]
 ...
 [ 0.06824137+0.j         -0.22661553+0.j          0.02950363+0.08123022j
  ... -0.02471705+0.j         -0.04867157+0.j
  -0.09933796+0.j        ]
 [ 0.06942537+0.j         -0.07301573+0.j          0.01103433-0.05313565j
  ... -0.10560006+0.j         -0.03454074+0.j
  -0.14776002+0.j        ]
 [ 0.0697126 +0.j          0.14484823+0.j          0.08215381+0.0190269j
  ... -0.10013533+0.j          0.02129835+0.j
  -0.02964213+0.j        ]]


<h3> Exercise 9.5: Singular values </h3>
<h4> Generate an n × n matrix, denoted by C, where each entry is 1 with probability p and 0 otherwise. Use
the linear algebra library of Scipy to compute the singular values of C. What can you say about the
relationship between n, p and the largest singular value? </h4>

In [20]:
p = 0.5
C = np.random.binomial(1, p, (n, n))
print("C: ")
print(C)
U, s, Vh = sl.svd(C)
print("Singular values of C: ")
print(s)
print("Largest singular value of C: ")
print(np.linalg.norm(C, 2))

C: 
[[1 0 0 ... 1 0 1]
 [1 0 1 ... 1 1 1]
 [0 0 0 ... 1 1 0]
 ...
 [0 1 1 ... 1 0 1]
 [0 0 1 ... 0 1 1]
 [0 0 1 ... 0 1 0]]
Singular values of C: 
[1.00172119e+02 1.40324787e+01 1.35704068e+01 1.35150585e+01
 1.33938673e+01 1.30336996e+01 1.29608056e+01 1.29213210e+01
 1.26860879e+01 1.26615043e+01 1.24765583e+01 1.23764645e+01
 1.21307643e+01 1.20749139e+01 1.20023962e+01 1.19606700e+01
 1.17878205e+01 1.17392207e+01 1.16019940e+01 1.15788297e+01
 1.13496833e+01 1.12472494e+01 1.11960033e+01 1.11368002e+01
 1.09663899e+01 1.08681302e+01 1.07849630e+01 1.07533881e+01
 1.07265681e+01 1.06696716e+01 1.05571572e+01 1.04566442e+01
 1.03317877e+01 1.02577773e+01 1.02123808e+01 1.00270021e+01
 9.95160534e+00 9.91124737e+00 9.82638322e+00 9.74797965e+00
 9.67820022e+00 9.62408585e+00 9.57458251e+00 9.53124849e+00
 9.39966716e+00 9.36484195e+00 9.32143876e+00 9.24785570e+00
 9.17446403e+00 9.10032569e+00 9.00249683e+00 8.98235259e+00
 8.92596136e+00 8.81538998e+00 8.77636203e+00 8.66995156e+00

<h3> Exercise 9.6: Nearest neighbor </h3>
<h4> Write a function that takes a value z and an array A and finds the element in A that is closest to z. The
function should return the closest value, not index.</h4>

In [21]:
def nearist_neighbor(A, z):
    return A[np.argmin(np.abs(A-z))]

A = np.random.rand(m)
print("A: ")
print(A)
z = 1
print("Nearist neighbor: ")
print(nearist_neighbor(A, z))


A: 
[0.42299075 0.60401256 0.24430195 0.96805408 0.69624122 0.43433593
 0.47262129 0.53417293 0.31450075 0.29999162 0.81707686 0.24589484
 0.4564764  0.31935057 0.88792754 0.38606054 0.91333773 0.85250323
 0.05608259 0.22288171 0.0324447  0.8444943  0.43920552 0.783293
 0.80618014 0.20811219 0.5119663  0.62021497 0.76681261 0.93082439
 0.20371624 0.69602816 0.91075388 0.98433453 0.06500696 0.91184827
 0.60162698 0.65723033 0.14706435 0.81687215 0.16767473 0.09789907
 0.09726018 0.40059109 0.98024657 0.27902252 0.67086874 0.59925605
 0.20063464 0.25007588 0.24627479 0.91452856 0.92851481 0.55094273
 0.94955338 0.70987351 0.81445697 0.72534734 0.22353114 0.693263
 0.94319433 0.85846848 0.7711066  0.70874261 0.87759503 0.2544335
 0.49642949 0.06531792 0.48281296 0.56603403 0.89138455 0.65671719
 0.22734343 0.86749318 0.27042499 0.79621385 0.10624785 0.86243383
 0.29498878 0.57149828 0.99973785 0.9500004  0.91242076 0.06449363
 0.94708209 0.894119   0.8977194  0.36877004 0.66500643 0.34723